name: Cabelas Price Tracker

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  check-price:
    runs-on: ubuntu-latest

    steps:
      - name: Download project
        uses: actions/checkout@v4

      - name: Run tracker
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python tracker.py
